# vision parameters
vision:
  target_class:           1
  confidence:             0.2

# Controller parameters 
controller:
  Kp:                     [200.0,200.0]
  Kd:                     [5.0,5.0]
  
  frequency:              1000        # Frequency of the control node
  time_delay:             0.1         # Expected time delay during fire (s)

  err_p_track:            1e-3        # Error threshold for tracking, position  (pixel)
  err_v_track:            1e-3        # Error threshold for tracking, velocity  (pixel/s)
  err_p_fire:             1e-3        # Error threshold for aim, position       (pixel)


# Estimator parameters 
estimator:
  camera:
    focal_length:         0.01
  kalman:
    q_acc:                1e+6
    r_detected:           25.0
    r_tracked:            25.0
    r_temp_vel:           100
    r_temp_acc:           400
    p0_pos:               900.0
    p0_vel:               100
    p0_acc:               400
    max_time_gap:         0.5

bridge:
  serial:
    name:                 "usb"
    port:                 "/dev/ttyUSB0"  # Read/write bridge frames
    baud:                 115200
    data_bits:            8
    stop_bits:            1
    parity:               0
    watchdog_frequency:   1000
