# vision parameters
vision:
  source:                 live
  topic_live:             /vision
  topic_test:             /vision/test
  image_topic:            /vision/image
  publish_state:          true
  publish_image:          true
  target_class:           1
  confidence:             0.2

# Controller parameters 
controller:
  Kp:                     [200.0,200.0]
  Kd:                     [5.0,5.0]
  
  frequency:              1000        # Frequency of the control node
  time_delay:             0.1         # Expected time delay during fire (s)

  err_p_track:            1e-3        # Error threshold for tracking, position  (pixel)
  err_v_track:            1e-3        # Error threshold for tracking, velocity  (pixel/s)
  err_p_fire:             1e-3        # Error threshold for aim, position       (pixel)


# Estimator parameters 
estimator:
  camera:
    focal_length:         0.01
  kalman:
    q_acc:                10000.0
    r_detected:           900.0
    r_tracked:            900.0
    r_temp_vel:           100.0
    r_temp_acc:           1000.0
    p0_pos:               900.0
    p0_vel:               900.0
    p0_acc:               4000.0
    max_time_gap:         0.5

bridge:
  serial:
    input:
      name:               ["joint0", "joint1"]
      port:               ["/dev/ttyUSB0", "/dev/ttyUSB1"]  # Joint data from encoder
      baud:               [115200, 115200]
      data_bits:          [8, 8]
      stop_bits:          [1, 1]
      parity:             [0, 0]

    output:
      name:               ["yaw", "pitch"]
      port:               ["/dev/ttyUSB3", "/dev/ttyUSB4"]  # Write joint data to motor
      baud:               [115200, 115200]
      data_bits:          [8, 8]
      stop_bits:          [1, 1]
      parity:             [0, 0]

    watchdog_frequency:   1000
